eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


stations: 
  station1:
    name: "Default"
    lane1:
      name:  "2-WHEELERS"
      price: "0.0"
    lane2:
      name: "4-WHEELERS"
      price: "0.0"
